name: dart_fire_midi
description: A library for communicating with a Akai Fire midi controller.
version: 0.3.0
homepage: http://github.com/maks/dart_fire_midi

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
